[package]
name = "Downloader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.18"
url = "2.2"
tokio = { version = "1.2.22", features = ["full"] }
regex = "1.8.1"
futures = "0.3.28"
